[package]
name = "musb"
version = "0.1.0"
edition = "2021"
authors = ["Decaday <myDecaday@outlook.com>"]
repository = "https://github.com/decaday/musb"
documentation = "https://docs.rs/musb"
homepage = "https://github.com/decaday/musb"
categories = ["embedded", "no-std", "hardware-support"]
description = "musb(Mentor USB) regs and `embassy-usb-driver` impl"
keywords = ["usb", "hal", "embedded", "no-std", "hardware-support"]
readme = "README.md"
license = "Apache-2.0"

[dependencies]
embassy-usb-driver = "0.1.0"
cfg-if = {version = "1.0.0", features = ["core"]}
embassy-sync = "0.6.1"


[build-dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
cfg-if = {version = "1.0.0"}

[features]
default = ["builtin-py32f07x", "prebuild"]
defmt = ["embassy-usb-driver/defmt", 
    "embassy-sync/defmt",
]

log = ["embassy-sync/log",]

builtin-py32f07x = []
builtin-py32f403 = []
builtin-std = []

prebuild = []

allow-ep-shared-fifo = []

endpoints-num-2 = []
endpoints-num-4 = []
endpoints-num-6 = []
endpoints-num-8 = []
endpoints-num-12 = []
endpoints-num-16 = []

# Interal features, auto-generated by build.rs according to profile
_ep-shared-fifo = []
_equal-fifo-size = []
_fixed-fifo-size = []

# Generate a `UsbInstance` when you set `base_address` in profile
_gen-usb-instance = []

[package.metadata.docs.rs]
features = ["defmt"]
targets = ["thumbv7em-none-eabihf"]
