[package]
name = "musb"
version = "0.0.1"
edition = "2021"
authors = ["Decaday <myDecaday@outlook.com>"]
repository = "https://github.com/decaday/musb"
documentation = "https://docs.rs/musb"
homepage = "https://github.com/decaday/musb"
categories = ["embedded", "no-std", "hardware-support"]
description = "Mentor usb Support"
keywords = ["usb", "hal", "embedded", "no-std", "hardware-support"]
readme = "README.md"
# license = "MIT OR Apache-2.0"

[dependencies]
