[package]
name = "musb"
version = "0.3.0"
edition = "2021"
authors = ["Decaday <myDecaday@outlook.com>"]
repository = "https://github.com/decaday/musb"
documentation = "https://docs.rs/musb"
homepage = "https://github.com/decaday/musb"
categories = ["embedded", "no-std", "hardware-support"]
description = "musb(Mentor USB) regs and `embassy-usb-driver`, `usb-device` impl"
keywords = ["usb", "hal", "embedded", "no-std", "hardware-support"]
readme = "README.md"
license = "Apache-2.0"
exclude = ["musb-readconf"]

[dependencies]
embassy-usb-driver = { version = "0.2.0" }
embassy-sync = { version = "0.7", optional = true }
usb-device = { version = "0.3.2", optional = true }

cfg-if = {version = "1.0.0", features = ["core"]}
defmt = { version = "1", optional = true }

[build-dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
cfg-if = {version = "1.0.0"}

[features]
default = ["prebuild"]

embassy-usb-driver-impl = ["embassy-sync"]
usb-device-impl = ["usb-device"]

defmt = ["embassy-usb-driver/defmt", 
    "embassy-sync/defmt",
    "usb-device/defmt",
    "dep:defmt",
]

log = ["embassy-sync/log", "usb-device/log"]

prebuild = []

builtin-std-8bep-2048 = []
builtin-py32f07x = ["_mini"]
builtin-py32f403 = ["_mini"]
builtin-sf32lb52x = []
# for musb-readconf only
builtin-readconf = []

# Interal features, auto-generated by build.rs according to profile
_ep-shared-fifo = []
_equal-fifo-size = []
_fixed-fifo-size = []
_mini = []
# Generate a `UsbInstance` when you set `base_address` in profile
_gen-usb-instance = []

[package.metadata.docs.rs]
features = ["defmt", "builtin-py32f07x", "embassy-usb-driver-impl"]
targets = ["thumbv7em-none-eabihf"]
