[package]
name = "musb-readconf"
version = "0.1.0"
edition = "2024"

[dependencies]
musb = { path = "../", default-features = false, features = ["builtin-readconf"] }
defmt = "0.3"

[features]
default = ["prebuild"]
prebuild = ["musb/prebuild"]