// This file is generated by build_src/gen.rs
use crate::info::EpDirection;
use crate::info::EpInfo;
pub const ENDPOINTS: [EpInfo; 8] = [
    EpInfo {
        ep_direction: EpDirection::RXTX,
        max_packet_size_dword: 8,
    },
    EpInfo {
        ep_direction: EpDirection::RXTX,
        max_packet_size_dword: 8,
    },
    EpInfo {
        ep_direction: EpDirection::RXTX,
        max_packet_size_dword: 8,
    },
    EpInfo {
        ep_direction: EpDirection::RXTX,
        max_packet_size_dword: 8,
    },
    EpInfo {
        ep_direction: EpDirection::RXTX,
        max_packet_size_dword: 8,
    },
    EpInfo {
        ep_direction: EpDirection::RXTX,
        max_packet_size_dword: 8,
    },
    EpInfo {
        ep_direction: EpDirection::RXTX,
        max_packet_size_dword: 8,
    },
    EpInfo {
        ep_direction: EpDirection::RXTX,
        max_packet_size_dword: 8,
    },
];
pub const TOTAL_FIFO_SIZE_DWORD: u32 = 256;
